apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-management-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: location-management
  template:
    metadata:
      labels:
        app: location-management
    spec:
      serviceAccountName: jenkins-sa  # Add this line to specify the service account
      containers:
      - name: location-management
        image: asmaarrak/location-management:latest
        ports:
        - containerPort: 3001
