apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-management
  template:
    metadata:
      labels:
        app: location-management
    spec:
      containers:
      - name: location-management
        image: asmaarrak/location-management:latest
        ports:
        - containerPort: 3001



apiVersion: v1
kind: Service
metadata:
  name: location-management-service
spec:
  selector:
    app: location-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
