apiVersion: v1
kind: Service
metadata:
  name: location-management-nodeport
spec:
  selector:
    app: location-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
