apiVersion: apps/v1
kind: Deployment
metadata:
  name: apgateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apgateway
  template:
    metadata:
      labels:
        app: apgateway
    spec:
      containers:
      - name: apgateway
        image: asmaarrak/apgateway:latest
        ports:
        - containerPort: 4000

        
apiVersion: v1
kind: Service
metadata:
  name: apgateway-service
spec:
  selector:
    app: apgateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort
