apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - name: user-auth
        image: asmaarrak/user-auth:latest
        ports:
        - containerPort: 3000


apiVersion: v1
kind: Service
metadata:
  name: user-authservice
spec:
  selector:
    app: user-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

