apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolvers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resolvers
  template:
    metadata:
      labels:
        app: resolvers
    spec:
      containers:
      - name: resolvers
        image: asmaarrak/resolvers:latest
        ports:
        - containerPort: 3002


apiVersion: v1
kind: Service
metadata:
  name: resolvers-service
spec:
  selector:
    app: resolvers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort

